# For more inspiration, look here:
# https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml

name: Build & Test

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * 3'
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - staging-squash-merge.tmp
    paths-ignore:
      - "**/docs/**"
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]
        cargo-cmd:
          - check --all-features
          - fmt --all -- --check
          - clippy --all-targets --all-features -- -D warnings
        exclude:
          - os: macos-latest
            toolchain: nightly
          - os: windows-latest
            toolchain: nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup | rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
          components: clippy, rustfmt
      #- name: Setup | CI dependencies
      #  run: sudo apt-get update; sudo apt-get install --no-install-recommends -y libasound2-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libudev-dev
      #  if: runner.os == 'linux'
      - uses: Swatinem/rust-cache@v1
      - run: cargo ${{ matrix['cargo-cmd'] }}

  test:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #os: [windows-latest, ubuntu-latest, macos-latest]
        toolchain: [stable]
        cargo-cmd:
          - test --all-features
          - build --package assets_example
          - build --package assets_manual_example
        #exclude:
        #  - os: macos-latest
        #    toolchain: nightly
        #  - os: windows-latest
        #    toolchain: nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup | rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      #- name: Setup | CI dependencies
      #  run: sudo apt-get update; sudo apt-get install --no-install-recommends -y libasound2-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libudev-dev
      #  if: runner.os == 'linux'
      - uses: Swatinem/rust-cache@v1
      - run: cargo ${{ matrix['cargo-cmd'] }}
